### ISSUE TITLE
[BUG] Colors are not inherited from parent folder

### ISSUE THREAD

**Issue by Libeccio84** [gbevan/color-tabs-byproject#8]
Despite setting **Folder Depth** default value to 1, i see the same tab color only for those files directly under project folder:
![image](https://user-images.githubusercontent.com/23318355/59847290-627dcb00-9362-11e9-8b58-3eee86445db2.png)

I have also tried to increase **Folder Depth** default value (_e.g._ 5) without success.
Shall someone help me?
I really need this feature, since I need more than one git repo in the same window and most files share their name.

Color Tabs Byproject version 1.2.3
Atom version 1.38.2 x64

Thanks in advance,
Dario

**Comment by gbevan** [comment]
Hi @Libeccio84, the default Folder Depth setting is 0 (zero) - pls try that, see if it does what you are expecting.
The setting Folder Depth was to allow manual color overrides for subfolders - it is probably being deprecated...

**Comment by Libeccio84** [comment]
No :(
It seems it is not enough. So no way to have the same tab color for each document inside project folder?
So far it seems to work only for those files directly under main folder...

**Comment by gbevan** [comment]
Strange, all files under a given project have the same color for me.  Can you please paste me a screenshot of your settings for this plugin?

**Comment by Libeccio84** [comment]
Here they are
<img width="960" alt="59928097-45b6c580-943e-11e9-93d0-2b54525110ad" src="https://user-images.githubusercontent.com/23318355/59945980-7e1fc900-9469-11e9-976d-d625ef0f9710.png">

:(

**Comment by gbevan** [comment]
Can you go into Packages -> Color Tabs By project -> Edit Rules and see if there are any saved overrides for the files/folders you are have an issue with (they may have persisted from the Folder Depth setting you previously had). Try closing all tabs and deleting any offending entries in the Rules file.

**Comment by gbevan** [comment]
Also, is it possible you have some other tab coloring plugin enabled that may be clashing?

**Comment by Libeccio84** [comment]
I have no other tab coloring plugin :(
In order to try it anew, I have removed you plugin (including its stored preferences and rule file), and I installed it again. Unfortunately nothing  has changed :((

**Comment by Libeccio84** [comment]
Good news!
Changing line
`projPath = path.replace(new RegExp("#{relPath}$"), "")`
with
`projPath = path.replace relPath, ""`
in `color-tabs-byproject\lib\color-tabs-byproject.coffee` solved the problem. Actually, with the first assignment `path` was not changed at all.

Now I have to fix the fact that the color I set is ignored, but the first step has been done :)
![image](https://user-images.githubusercontent.com/23318355/59946151-056d3c80-946a-11e9-97a2-090177ed3db9.png)

**Comment by Libeccio84** [comment]
Ok, I have realized :)
It was a matter of mistyping: I missed `\\` in project path and `:` at the end of the path itself.
Now it works as expected.
To summarize: I had to change
`projPath = path.replace(new RegExp("#{relPath}$"), "")`
with
`projPath = path.replace relPath, ""`
in `color-tabs-byproject\lib\color-tabs-byproject.coffee` and everything worked as expected :)

Bye!

**Comment by gbevan** [comment]
Thanks for that @Libeccio84 i understand the issue now - there will be a patch release soon.  The underlying issue was that i wasnt escaping `\`'s in windows folder names...  (my use case for Atom is primarily on linux...)

**Comment by Libeccio84** [comment]
If there are no underlying reasons I am not aware of, shall you give the possibility to refer the project directly from projName? it is easier for user: no `\` escaping needed... :P

Thanks anyway, I am looking forward for the patch :)

**Comment by gbevan** [comment]
Released 1.2.7, let me know if you still have issues

**Comment by Libeccio84** [comment]
Now it works, many thanks!
